### PR TITLE
Basic Object Destructuring

### PR DESCRIPTION
**Pull request by BobVarioa**
Title, object destructuring, except rest patterns as I'm not really sure how to implement those well (probably some builtin? but seems like it would be particularly jank with how we are currently doing it)

### CODE REVIEW

**Comment by CanadaHonk** [comment]
Probably out of scope for this PR but to note we will have to support destructuring in other places at some point (assignment, for..of, etc)

**Comment by BobVarioa** [comment]
Maybe we could move some of this logic to `allocVar`?

**Comment by CanadaHonk** [comment]
Possibly, I'm not sure how deduplicable this code is. Hopefully it is :pray:

**Comment by CanadaHonk** [comment]
Merging manually to add test262 data

**Pull request merged**
